formula:  公式
sources:
    - source: hdfs
      path: /xx/xxx/xxx
      dataType: text
      columnSplitSymbol: \t
      variables:
        公式变量名1:
           num: 1
           dataType: json
           param: age
           paramType: Double
        公式变量名2:
           num: 0
           dataType: Double
    - source: hdfs
      path: /xx/xxx/xxx
      dataType: json
      variables:
        公式变量名2:
          dataType: json
          param: house.total_showing_cnt
          paramType: Double
    - source: mysql
      ip: ip
      port: port
      database: database
      tables:
        - table: 表名
           - columns:
                a:
                  name: 字段名
                  dataType: 字段类型


out:
  type: hdfs
  path: /xx/xx

